name: YouTube Live Streaming with Video URLs

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg curl

      - name: Stream to YouTube
        run: |
          YOUTUBE_STREAM_KEY=$(cat youtube_stream_key.txt)
          AUDIO_URL="https://dev.plusmusica.dom/indah.webm"

          while true; do
            while IFS= read -r VIDEO_URL; do
              echo "Streaming video: $VIDEO_URL"
              ffmpeg -re -i "$VIDEO_URL" -i "$AUDIO_URL" -c:v copy -c:a aac -shortest -f flv "rtmp://a.rtmp.youtube.com/live2/$YOUTUBE_STREAM_KEY"
            done < video_urls.txt
          done
