name: YouTube Live Streaming

on:
  workflow_dispatch

jobs:
  stream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          curl https://rclone.org/install.sh | sudo bash

      - name: Stream to YouTube
        run: |
          YOUTUBE_STREAM_KEY=$(cat youtube_stream_key.txt)
          FOLDER_ID=$(cat input_folder_id.txt)
          
          # Copy video dari Google Drive
          rclone copy "gdrive:$FOLDER_ID/indah.mp4" ./ --config gdrive_credentials.json
          
          # Stream ke YouTube
          ffmpeg -re -i "indah.mp4" -c:v copy -c:a copy -f flv "rtmp://a.rtmp.youtube.com/live2/$YOUTUBE_STREAM_KEY"
