name: YouTube Live Streaming

on:
  workflow_dispatch

jobs:
  stream:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone/
          cat > ~/.config/rclone/rclone.conf << 'EOF'
          [gdrive]
          type = drive
          scope = drive
          service_account_file = /home/runner/work/live/live/gdrive_credentials.json
          root_folder_id = 1hN8CsqGJ-8mtPR4m3BmAaoZ1ZrN1dwXC
          EOF
          
          # Set permission
          chmod 600 ~/.config/rclone/rclone.conf
          chmod 600 gdrive_credentials.json

      - name: Stream to YouTube
        run: |
          YOUTUBE_STREAM_KEY=$(cat youtube_stream_key.txt)
          
          # Copy video dari Google Drive menggunakan absolute path
          rclone copy "gdrive:indah.mp4" ./ --drive-service-account-file=/home/runner/work/live/live/gdrive_credentials.json --progress
          
          # Stream ke YouTube
          ffmpeg -re -i "indah.mp4" -c:v copy -c:a copy -f flv "rtmp://a.rtmp.youtube.com/live2/$YOUTUBE_STREAM_KEY"
